In [26]:
import pandas as pd
import requests
df = pd.read_csv("../data/trips.txt")

#Route: Silver
#Stops: PAR, Goodwin and Gregory, Gregory and Mumford, Illini Union
#trip_id: [@6.0.28932250@][1][1654525597845]/57__SV1_UIF
# scheduled vs expected = delay


#create a .py file 
#create a .csv file to write data
# run a while true function
# every time request, keep a timestamp of the request
# run as a background progress
#request and then sleep for a minute
df.head(10)

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,SILVER,SV1 UIF,[@6.0.28932250@][1][1654525597845]/57__SV1_UIF,North to PAR,NaN,0,SV1 UIF,[@6.0.28932250@]1,1,1
1,SILVER LATE NIGHT,SV1 UIMTH,[@12.0.42230752@][4][1246897581031]/20__SV1_UIMTH,South to PAR,NaN,1,SV1 UIMTH,SILVER LATE 30,1,1
2,PINK,P2 NOSCH MF,[@2.0.81838518@][12][1430161301181]/27__P2_NOS...,B to Round Barn Road,NaN,1,P2 NOSCH MF,[@2.0.81838518@]103,1,1
3,TEAL EVENING SATURDAY,T2 UI SA,[@124.0.92279199@][1484345597711]/38__T2_UI_SA,West to Illinois Terminal,NaN,1,T2 UI SA,[@124.0.92279199@]TEAL EVENING 12,1,1
4,GREEN,GN5 MF,5GN575__GN5_MF,West to Round Barn Road - Holiday Park,NaN,1,GN5 MF,5WPM->LSE,1,1
5,SILVER,SV4 SCH UIMTH,[@6.0.28932250@][1][1654213811517]/48__SV4_SCH...,North to Lincoln Square,NaN,0,SV4 SCH UIMTH,[@6.0.28932250@]1,1,1
6,ILLINI EVENING SATURDAY,I3 UISA,[@124.0.92260187@][1484328831455]/256__I3_UISA,North to Lincoln & Killarney,NaN,0,I3 UISA,[@124.0.92260187@]220N ILLINI 10,1,1
7,ILLINI,I1 UIMF,[@7.0.41200832@][1][1238430123625]/53__I1_UIMF,North to Lincoln & Anthony,NaN,0,I1 UIMF,[@15.0.63192528@]43,1,1
8,GREEN SATURDAY,GN3 UISA,[@7.0.41202550@][4][1248723584250]/1__GN3_UISA,West to Round Barn Road,NaN,1,GN3 UISA,[@15.0.68513015@]219,1,1
9,ILLINI LIMITED,I1 NONUI EVE,[@6.0.14327389@][1][1622146809102]/12__I1_NONU...,North to Lincoln & Killarney,NaN,0,I1 NONUI EVE,[@6.0.14327389@]10,1,1

In [27]:
df_stoptimes = pd.read_csv("../data/stop_times.txt")
df_stoptimes[df_stoptimes["trip_id"] == "[@6.0.28932250@][1][1654213811517]/48__SV4_SCH_UIMTH"]
df_stoptimes["route_name"] = "Silver"
df_stoptimes.head(20)

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,timepoint,route_name
0,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:26:00,19:26:00,PAR:2,1,NaN,0,0,0,Silver
1,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:00,19:27:00,PAMD:2,2,NaN,0,0,0,Silver
2,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:45,19:27:45,PSL:2,3,NaN,0,0,0,Silver
3,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:28:20,19:28:20,GRGDNR:2,4,NaN,0,0,0,Silver
4,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:28:55,19:28:55,GWNGRG:1,5,NaN,0,0,0,Silver
5,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:29:30,19:29:30,GRGMUM:2,6,NaN,0,0,0,Silver
6,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:30:05,19:30:05,GRGLIB:2,7,NaN,0,0,0,Silver
7,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:31:15,19:31:15,ARYWRT:5,8,NaN,0,0,0,Silver
8,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:31:50,19:31:50,PLAZA:4,9,NaN,0,0,0,Silver
9,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:33:00,19:33:00,IU:1,10,NaN,0,0,0,Silver
10,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:34:30,19:34:30,GDWNMRL:2,11,NaN,0,0,0,Silver
11,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:35:00,19:35:00,SPFLDHVY:3,12,NaN,0,0,0,Silver
12,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:35:30,19:35:30,SPFLDGRGST:3,13,NaN,0,0,0,Silver
13,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:36:30,19:36:30,SPFLDBSY:3,14,NaN,0,0,0,Silver
14,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:37:30,19:37:30,SPFLDPRC:1,15,NaN,0,0,0,Silver
15,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:38:00,19:38:00,SPFLDBRCH:3,16,NaN,0,0,0,Silver
16,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:40:00,19:40:00,LSE:8,17,NaN,0,0,0,Silver
17,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:26:00,19:26:00,PAR:2,1,NaN,0,0,0,Silver
18,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:00,19:27:00,PAMD:2,2,NaN,0,0,0,Silver
19,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:45,19:27:45,PSL:2,3,NaN,0,0,0,Silver

In [28]:
url = "https://developer.mtd.org/api/v2.2/json/getdeparturesbystop?key=c097f4c423e7471eb40a606d859ce9e0&stop_id=GRGMUM:2"

In [29]:
response = requests.get(url)
data = response.json()
departures = data["departures"]
df_departures = pd.DataFrame(departures)

In [30]:
df_departures

Empty DataFrame
Columns: []
Index: []

In [31]:
stops = ["PAR:2", "ARYWRT:5", "PLAZA:4", "IU:1", "LSE:8"]
all_departures = []

for stop in stops:
    url = f"https://developer.mtd.org/api/v2.2/json/getdeparturesbystop?key=c097f4c423e7471eb40a606d859ce9e0&stop_id={stop}"
    response = requests.get(url)
    data = response.json()
    departures = data.get("departures", [])

    df_res = pd.DataFrame(departures)

    if not df_res.empty:
        print(df_res.info())

        df_res["expected"] = pd.to_datetime(df_res["expected"], errors="coerce")
        df_res["scheduled"] = pd.to_datetime(df_res["scheduled"], errors="coerce")

        df_res["delay"] = df_res["expected"] - df_res["scheduled"]
        df_res["queried_stop"] = stop

        all_departures.append(df_res)

df_all = pd.concat(all_departures, ignore_index=True)

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stop_id        1 non-null      str
 1   headsign       1 non-null      str
 2   route          1 non-null      object
 3   trip           1 non-null      object
 4   vehicle_id     1 non-null      str
 5   origin         1 non-null      object
 6   destination    1 non-null      object
 7   is_monitored   1 non-null      bool
 8   is_scheduled   1 non-null      bool
 9   is_istop       1 non-null      bool
 10  scheduled      1 non-null      str
 11  expected       1 non-null      str
 12  expected_mins  1 non-null      int64
 13  location       1 non-null      object
dtypes: bool(3), int64(1), object(5), str(5)
memory usage: 223.0+ bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stop_id        2 non-null      str
 1   headsign       2 non-null      str
 2   route          2 non-null      object
 3   trip           2 non-null      object
 4   vehicle_id     2 non-null      str
 5   origin         2 non-null      object
 6   destination    2 non-null      object
 7   is_monitored   2 non-null      bool
 8   is_scheduled   2 non-null      bool
 9   is_istop       2 non-null      bool
 10  scheduled      2 non-null      str
 11  expected       2 non-null      str
 12  expected_mins  2 non-null      int64
 13  location       2 non-null      object
dtypes: bool(3), int64(1), object(5), str(5)
memory usage: 314.0+ bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stop_id        4 non-null      str
 1   headsign       4 non-null      str
 2   route          4 non-null      object
 3   trip           4 non-null      object
 4   vehicle_id     4 non-null      str
 5   origin         4 non-null      object
 6   destination    4 non-null      object
 7   is_monitored   4 non-null      bool
 8   is_scheduled   4 non-null      bool
 9   is_istop       4 non-null      bool
 10  scheduled      4 non-null      str
 11  expected       4 non-null      str
 12  expected_mins  4 non-null      int64
 13  location       4 non-null      object
dtypes: bool(3), int64(1), object(5), str(5)
memory usage: 496.0+ bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stop_id        1 non-null      str
 1   headsign       1 non-null      str
 2   route          1 non-null      object
 3   trip           1 non-null      object
 4   vehicle_id     1 non-null      str
 5   origin         1 non-null      object
 6   destination    1 non-null      object
 7   is_monitored   1 non-null      bool
 8   is_scheduled   1 non-null      bool
 9   is_istop       1 non-null      bool
 10  scheduled      1 non-null      str
 11  expected       1 non-null      str
 12  expected_mins  1 non-null      int64
 13  location       1 non-null      object
dtypes: bool(3), int64(1), object(5), str(5)
memory usage: 223.0+ bytes
None

In [32]:
df_all

,stop_id,headsign,route,trip,vehicle_id,origin,destination,is_monitored,is_scheduled,is_istop,scheduled,expected,expected_mins,location,delay,queried_stop
0,ARYWRT:5,130S Silver Limited,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@15.0.67924657@][2][136372872594...,null,{'stop_id': 'LSE:8'},{'stop_id': 'PLAZA:4'},False,True,True,2026-03-20 23:54:15-05:00,2026-03-20 23:54:15-05:00,9,"{'lat': 0, 'lon': 0}",0 days,ARYWRT:5
1,PLAZA:4,220N Illini Limited,"{'route_color': '5a1d5a', 'route_id': 'ILLINI ...",{'trip_id': '[@6.0.14328849@][1][1622466962641...,null,{'stop_id': 'ARC:2'},{'stop_id': 'LNCLNKLRNY:1'},False,True,True,2026-03-20 23:46:00-05:00,2026-03-20 23:46:00-05:00,1,"{'lat': 0, 'lon': 0}",0 days,PLAZA:4
2,PLAZA:4,130N Silver Limited,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@15.0.67924657@][1][136372575497...,null,{'stop_id': 'PLAZA:4'},{'stop_id': 'LSE:8'},False,True,True,2026-03-20 23:55:00-05:00,2026-03-20 23:55:00-05:00,10,"{'lat': 0, 'lon': 0}",0 days,PLAZA:4
3,IU:1,220N Illini Limited,"{'route_color': '5a1d5a', 'route_id': 'ILLINI ...",{'trip_id': '[@6.0.14328849@][1][1622466962641...,null,{'stop_id': 'ARC:2'},{'stop_id': 'LNCLNKLRNY:1'},False,True,True,2026-03-20 23:48:00-05:00,2026-03-20 23:48:00-05:00,3,"{'lat': 0, 'lon': 0}",0 days,IU:1
4,IU:1,50E Green Lsq,"{'route_color': '008063', 'route_id': 'GREEN E...",{'trip_id': '[@7.0.41201218@][3][1243953924046...,null,{'stop_id': 'RNDBRNRD:2'},{'stop_id': 'LSE:1'},False,True,False,2026-03-20 23:49:00-05:00,2026-03-20 23:49:00-05:00,4,"{'lat': 0, 'lon': 0}",0 days,IU:1
5,IU:1,130N Silver Limited,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@15.0.67924657@][1][136372575497...,null,{'stop_id': 'PLAZA:4'},{'stop_id': 'LSE:8'},False,True,True,2026-03-20 23:57:00-05:00,2026-03-20 23:57:00-05:00,12,"{'lat': 0, 'lon': 0}",0 days,IU:1
6,IU:1,120E Teal Orchard Downs,"{'route_color': '006991', 'route_id': 'TEAL EV...",{'trip_id': '[@7.0.41903462@][3][1243545711640...,null,{'stop_id': 'IT:5'},{'stop_id': 'ODSS:1'},False,True,True,2026-03-21 00:02:00-05:00,2026-03-21 00:02:00-05:00,17,"{'lat': 0, 'lon': 0}",0 days,IU:1
7,LSE:8,130S Silver Limited,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@15.0.67924657@][2][136372872594...,null,{'stop_id': 'LSE:8'},{'stop_id': 'PLAZA:4'},False,True,False,2026-03-20 23:45:00-05:00,2026-03-20 23:45:00-05:00,0,"{'lat': 0, 'lon': 0}",0 days,LSE:8

In [33]:
import io

resp = requests.get(
	"https://waf.cs.illinois.edu/discovery/course-catalog.csv",
	verify=False,  # disable SSL cert verification to avoid CERTIFICATE_VERIFY_FAILED
)
courses = pd.read_csv(io.StringIO(resp.text))

/Users/zihanliu/SIGaida guided_project/sigaida-guided-project/venv/lib/python3.14/site-packages/urllib3/connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'waf.cs.illinois.edu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [34]:
print(courses.columns)
print(courses["Credit Hours"].head(10))
print(courses["Credit Hours"].dtype)

Index(['Year', 'Term', 'YearTerm', 'Subject', 'Number', 'Name', 'Description',
       'Credit Hours', 'Section Info', 'Degree Attributes',
       'Schedule Information', 'CRN', 'Section', 'Status Code', 'Part of Term',
       'Section Title', 'Section Credit Hours', 'Section Status',
       'Enrollment Status', 'Type', 'Type Code', 'Start Time', 'End Time',
       'Days of Week', 'Room', 'Building', 'Instructors'],
      dtype='str')
0    3 hours.
1    3 hours.
2    3 hours.
3    3 hours.
4    3 hours.
5    3 hours.
6    3 hours.
7    3 hours.
8    3 hours.
9    3 hours.
Name: Credit Hours, dtype: str
str

In [35]:
courses.info()

<class 'pandas.DataFrame'>
RangeIndex: 12823 entries, 0 to 12822
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  12823 non-null  int64
 1   Term                  12823 non-null  str
 2   YearTerm              12823 non-null  str
 3   Subject               12823 non-null  str
 4   Number                12823 non-null  int64
 5   Name                  12823 non-null  str
 6   Description           12822 non-null  str
 7   Credit Hours          12823 non-null  str
 8   Section Info          11627 non-null  str
 9   Degree Attributes     2536 non-null   str
 10  Schedule Information  2725 non-null   str
 11  CRN                   12823 non-null  int64
 12  Section               12176 non-null  str
 13  Status Code           12823 non-null  str
 14  Part of Term          12595 non-null  str
 15  Section Title         1766 non-null   str
 16  Section Credit Hours  3257 non-null   str
 17  Section Status        12823 non-null  str
 18  Enrollment Status     12823 non-null  str
 19  Type                  12823 non-null  str
 20  Type Code             12823 non-null  str
 21  Start Time            12823 non-null  str
 22  End Time              9688 non-null   str
 23  Days of Week          9857 non-null   str
 24  Room                  8842 non-null   str
 25  Building              8884 non-null   str
 26  Instructors           11901 non-null  str
dtypes: int64(3), str(24)
memory usage: 2.6 MB