In [1]:
import pandas as pd
import requests
df = pd.read_csv("../data/trips.txt")

#Route: Silver
#Stops: PAR, Goodwin and Gregory, Gregory and Mumford, Illini Union
#trip_id: [@6.0.28932250@][1][1654525597845]/57__SV1_UIF
# scheduled vs expected = delay


#create a .py file 
#create a .csv file to write data
# run a while true function
# every time request, keep a timestamp of the request
# run as a background progress
#request and then sleep for a minute
df.head(10)

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,SILVER,SV1 UIF,[@6.0.28932250@][1][1654525597845]/57__SV1_UIF,North to PAR,NaN,0,SV1 UIF,[@6.0.28932250@]1,1,1
1,SILVER LATE NIGHT,SV1 UIMTH,[@12.0.42230752@][4][1246897581031]/20__SV1_UIMTH,South to PAR,NaN,1,SV1 UIMTH,SILVER LATE 30,1,1
2,PINK,P2 NOSCH MF,[@2.0.81838518@][12][1430161301181]/27__P2_NOS...,B to Round Barn Road,NaN,1,P2 NOSCH MF,[@2.0.81838518@]103,1,1
3,TEAL EVENING SATURDAY,T2 UI SA,[@124.0.92279199@][1484345597711]/38__T2_UI_SA,West to Illinois Terminal,NaN,1,T2 UI SA,[@124.0.92279199@]TEAL EVENING 12,1,1
4,GREEN,GN5 MF,5GN575__GN5_MF,West to Round Barn Road - Holiday Park,NaN,1,GN5 MF,5WPM->LSE,1,1
5,SILVER,SV4 SCH UIMTH,[@6.0.28932250@][1][1654213811517]/48__SV4_SCH...,North to Lincoln Square,NaN,0,SV4 SCH UIMTH,[@6.0.28932250@]1,1,1
6,ILLINI EVENING SATURDAY,I3 UISA,[@124.0.92260187@][1484328831455]/256__I3_UISA,North to Lincoln & Killarney,NaN,0,I3 UISA,[@124.0.92260187@]220N ILLINI 10,1,1
7,ILLINI,I1 UIMF,[@7.0.41200832@][1][1238430123625]/53__I1_UIMF,North to Lincoln & Anthony,NaN,0,I1 UIMF,[@15.0.63192528@]43,1,1
8,GREEN SATURDAY,GN3 UISA,[@7.0.41202550@][4][1248723584250]/1__GN3_UISA,West to Round Barn Road,NaN,1,GN3 UISA,[@15.0.68513015@]219,1,1
9,ILLINI LIMITED,I1 NONUI EVE,[@6.0.14327389@][1][1622146809102]/12__I1_NONU...,North to Lincoln & Killarney,NaN,0,I1 NONUI EVE,[@6.0.14327389@]10,1,1

In [2]:
df_stoptimes = pd.read_csv("../data/stop_times.txt")
df_stoptimes[df_stoptimes["trip_id"] == "[@6.0.28932250@][1][1654213811517]/48__SV4_SCH_UIMTH"]
df_stoptimes["route_name"] = "Silver"
df_stoptimes.head(20)

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,timepoint,route_name
0,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:26:00,19:26:00,PAR:2,1,NaN,0,0,0,Silver
1,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:00,19:27:00,PAMD:2,2,NaN,0,0,0,Silver
2,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:45,19:27:45,PSL:2,3,NaN,0,0,0,Silver
3,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:28:20,19:28:20,GRGDNR:2,4,NaN,0,0,0,Silver
4,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:28:55,19:28:55,GWNGRG:1,5,NaN,0,0,0,Silver
5,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:29:30,19:29:30,GRGMUM:2,6,NaN,0,0,0,Silver
6,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:30:05,19:30:05,GRGLIB:2,7,NaN,0,0,0,Silver
7,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:31:15,19:31:15,ARYWRT:5,8,NaN,0,0,0,Silver
8,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:31:50,19:31:50,PLAZA:4,9,NaN,0,0,0,Silver
9,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:33:00,19:33:00,IU:1,10,NaN,0,0,0,Silver
10,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:34:30,19:34:30,GDWNMRL:2,11,NaN,0,0,0,Silver
11,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:35:00,19:35:00,SPFLDHVY:3,12,NaN,0,0,0,Silver
12,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:35:30,19:35:30,SPFLDGRGST:3,13,NaN,0,0,0,Silver
13,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:36:30,19:36:30,SPFLDBSY:3,14,NaN,0,0,0,Silver
14,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:37:30,19:37:30,SPFLDPRC:1,15,NaN,0,0,0,Silver
15,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:38:00,19:38:00,SPFLDBRCH:3,16,NaN,0,0,0,Silver
16,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:40:00,19:40:00,LSE:8,17,NaN,0,0,0,Silver
17,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:26:00,19:26:00,PAR:2,1,NaN,0,0,0,Silver
18,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:00,19:27:00,PAMD:2,2,NaN,0,0,0,Silver
19,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:45,19:27:45,PSL:2,3,NaN,0,0,0,Silver

In [3]:
url = "https://developer.mtd.org/api/v2.2/json/getdeparturesbystop?key=c097f4c423e7471eb40a606d859ce9e0&stop_id=GRGMUM:2"

In [4]:
response = requests.get(url)
data = response.json()
departures = data["departures"]
df_departures = pd.DataFrame(departures)
print (data)

{'time': '2026-04-11T15:30:56-05:00', 'new_changeset': True, 'status': {'code': 200, 'msg': 'ok'}, 'rqst': {'method': 'GetDeparturesByStop', 'params': {'stop_id': 'GRGMUM:2'}}, 'departures': [{'stop_id': 'GRGMUM:2', 'headsign': '130N Silver', 'route': {'route_color': 'cccccc', 'route_id': 'SILVER SATURDAY', 'route_long_name': 'Silver Saturday', 'route_short_name': '130', 'route_text_color': '000000'}, 'trip': {'trip_id': '[@12.0.44184681@][1250945403296]/86__SV1_UISA', 'trip_headsign': 'Lincoln Square', 'route_id': 'SILVER SATURDAY', 'block_id': 'SV1 UISA', 'direction': 'North', 'service_id': 'SV1 UISA', 'shape_id': '130N SILVER WEEKEND 2'}, 'vehicle_id': '2432', 'origin': {'stop_id': 'PAR:2'}, 'destination': {'stop_id': 'ILBDWY:1'}, 'is_monitored': True, 'is_scheduled': True, 'is_istop': True, 'scheduled': '2026-04-11T15:29:30-05:00', 'expected': '2026-04-11T15:31:59-05:00', 'expected_mins': 1, 'location': {'lat': 40.104033, 'lon': -88.221833}}, {'stop_id': 'GRGMUM:2', 'headsign': '130N Silver', 'route': {'route_color': 'cccccc', 'route_id': 'SILVER SATURDAY', 'route_long_name': 'Silver Saturday', 'route_short_name': '130', 'route_text_color': '000000'}, 'trip': {'trip_id': '[@12.0.44184681@][1250945403296]/87__SV2_UISA', 'trip_headsign': 'Lincoln Square', 'route_id': 'SILVER SATURDAY', 'block_id': 'SV2 UISA', 'direction': 'North', 'service_id': 'SV2 UISA', 'shape_id': '130N SILVER WEEKEND 1'}, 'vehicle_id': '1354', 'origin': {'stop_id': 'VETMED:1'}, 'destination': {'stop_id': 'ILBDWY:1'}, 'is_monitored': True, 'is_scheduled': True, 'is_istop': True, 'scheduled': '2026-04-11T15:49:30-05:00', 'expected': '2026-04-11T15:52:10-05:00', 'expected_mins': 21, 'location': {'lat': 40.11286, 'lon': -88.217167}}]}

In [5]:
df_departures

,stop_id,headsign,route,trip,vehicle_id,origin,destination,is_monitored,is_scheduled,is_istop,scheduled,expected,expected_mins,location
0,GRGMUM:2,130N Silver,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@12.0.44184681@][1250945403296]/...,2432,{'stop_id': 'PAR:2'},{'stop_id': 'ILBDWY:1'},True,True,True,2026-04-11T15:29:30-05:00,2026-04-11T15:31:59-05:00,1,"{'lat': 40.104033, 'lon': -88.221833}"
1,GRGMUM:2,130N Silver,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@12.0.44184681@][1250945403296]/...,1354,{'stop_id': 'VETMED:1'},{'stop_id': 'ILBDWY:1'},True,True,True,2026-04-11T15:49:30-05:00,2026-04-11T15:52:10-05:00,21,"{'lat': 40.11286, 'lon': -88.217167}"

In [6]:
stops = ["PAR:2", "ARYWRT:5", "PLAZA:4", "IU:1", "LSE:8"]
all_departures = []

for stop in stops:
    url = f"https://developer.mtd.org/api/v2.2/json/getdeparturesbystop?key=c097f4c423e7471eb40a606d859ce9e0&stop_id={stop}"
    response = requests.get(url)
    data = response.json()
    departures = data.get("departures", [])

    df_res = pd.DataFrame(departures)

    if not df_res.empty:
        print(df_res.info())

        df_res["expected"] = pd.to_datetime(df_res["expected"], errors="coerce")
        df_res["scheduled"] = pd.to_datetime(df_res["scheduled"], errors="coerce")

        df_res["delay"] = df_res["expected"] - df_res["scheduled"]
        df_res["queried_stop"] = stop

        all_departures.append(df_res)

df_all = pd.concat(all_departures, ignore_index=True)

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stop_id        2 non-null      str
 1   headsign       2 non-null      str
 2   route          2 non-null      object
 3   trip           2 non-null      object
 4   vehicle_id     2 non-null      str
 5   origin         2 non-null      object
 6   destination    2 non-null      object
 7   is_monitored   2 non-null      bool
 8   is_scheduled   2 non-null      bool
 9   is_istop       2 non-null      bool
 10  scheduled      2 non-null      str
 11  expected       2 non-null      str
 12  expected_mins  2 non-null      int64
 13  location       2 non-null      object
dtypes: bool(3), int64(1), object(5), str(5)
memory usage: 314.0+ bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stop_id        4 non-null      str
 1   headsign       4 non-null      str
 2   route          4 non-null      object
 3   trip           4 non-null      object
 4   vehicle_id     4 non-null      str
 5   origin         4 non-null      object
 6   destination    4 non-null      object
 7   is_monitored   4 non-null      bool
 8   is_scheduled   4 non-null      bool
 9   is_istop       4 non-null      bool
 10  scheduled      4 non-null      str
 11  expected       4 non-null      str
 12  expected_mins  4 non-null      int64
 13  location       4 non-null      object
dtypes: bool(3), int64(1), object(5), str(5)
memory usage: 496.0+ bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stop_id        4 non-null      str
 1   headsign       4 non-null      str
 2   route          4 non-null      object
 3   trip           4 non-null      object
 4   vehicle_id     4 non-null      str
 5   origin         4 non-null      object
 6   destination    4 non-null      object
 7   is_monitored   4 non-null      bool
 8   is_scheduled   4 non-null      bool
 9   is_istop       4 non-null      bool
 10  scheduled      4 non-null      str
 11  expected       4 non-null      str
 12  expected_mins  4 non-null      int64
 13  location       4 non-null      object
dtypes: bool(3), int64(1), object(5), str(5)
memory usage: 496.0+ bytes
None
<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stop_id        7 non-null      str
 1   headsign       7 non-null      str
 2   route          7 non-null      object
 3   trip           7 non-null      object
 4   vehicle_id     6 non-null      str
 5   origin         7 non-null      object
 6   destination    7 non-null      object
 7   is_monitored   7 non-null      bool
 8   is_scheduled   7 non-null      bool
 9   is_istop       7 non-null      bool
 10  scheduled      7 non-null      str
 11  expected       7 non-null      str
 12  expected_mins  7 non-null      int64
 13  location       7 non-null      object
dtypes: bool(3), int64(1), object(5), str(5)
memory usage: 769.0+ bytes
None

In [7]:
df_all

,stop_id,headsign,route,trip,vehicle_id,origin,destination,is_monitored,is_scheduled,is_istop,scheduled,expected,expected_mins,location,delay,queried_stop
0,PAR:2,120W Teal,"{'route_color': '006991', 'route_id': 'TEAL SA...",{'trip_id': '[@12.0.44194660@][1250946648828]/...,1835,{'stop_id': 'ODSS:1'},{'stop_id': 'IT:5'},True,True,True,2026-04-11 15:41:00-05:00,2026-04-11 15:48:18-05:00,17,"{'lat': 40.110433, 'lon': -88.224683}",0 days 00:07:18,PAR:2
1,PAR:2,130N Silver,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@12.0.44184681@][1250945403296]/...,1354,{'stop_id': 'VETMED:1'},{'stop_id': 'ILBDWY:1'},True,True,True,2026-04-11 15:46:00-05:00,2026-04-11 15:48:40-05:00,18,"{'lat': 40.11286, 'lon': -88.217167}",0 days 00:02:40,PAR:2
2,ARYWRT:5,130N Silver,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@12.0.44184681@][1250945403296]/...,2432,{'stop_id': 'PAR:2'},{'stop_id': 'ILBDWY:1'},True,True,True,2026-04-11 15:31:15-05:00,2026-04-11 15:33:44-05:00,3,"{'lat': 40.104033, 'lon': -88.221833}",0 days 00:02:29,ARYWRT:5
3,ARYWRT:5,220N Illini Limited,"{'route_color': '5a1d5a', 'route_id': 'ILLINI ...",{'trip_id': '[@6.0.14330204@][1][1622384291845...,2019,{'stop_id': 'ARC:2'},{'stop_id': 'LNCLNKLRNY:1'},True,True,True,2026-04-11 15:25:00-05:00,2026-04-11 15:36:15-05:00,5,"{'lat': 40.101467, 'lon': -88.2385}",0 days 00:11:15,ARYWRT:5
4,ARYWRT:5,130N Silver,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@12.0.44184681@][1250945403296]/...,1354,{'stop_id': 'VETMED:1'},{'stop_id': 'ILBDWY:1'},True,True,True,2026-04-11 15:51:15-05:00,2026-04-11 15:53:55-05:00,23,"{'lat': 40.11286, 'lon': -88.217167}",0 days 00:02:40,ARYWRT:5
5,ARYWRT:5,100N Yellow,"{'route_color': 'fcee1f', 'route_id': 'YELLOW ...",{'trip_id': '[@15.0.63192124@][1][133841428066...,2421,{'stop_id': 'SWALMART:1'},{'stop_id': 'WALMART:2'},True,True,True,2026-04-11 15:56:00-05:00,2026-04-11 15:56:36-05:00,26,"{'lat': 40.0689, 'lon': -88.240883}",0 days 00:00:36,ARYWRT:5
6,PLAZA:4,130N Silver,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@12.0.44184681@][1250945403296]/...,2432,{'stop_id': 'PAR:2'},{'stop_id': 'ILBDWY:1'},True,True,True,2026-04-11 15:32:00-05:00,2026-04-11 15:34:29-05:00,4,"{'lat': 40.104033, 'lon': -88.221833}",0 days 00:02:29,PLAZA:4
7,PLAZA:4,220N Illini Limited,"{'route_color': '5a1d5a', 'route_id': 'ILLINI ...",{'trip_id': '[@6.0.14330204@][1][1622384291845...,2019,{'stop_id': 'ARC:2'},{'stop_id': 'LNCLNKLRNY:1'},True,True,True,2026-04-11 15:26:00-05:00,2026-04-11 15:37:15-05:00,6,"{'lat': 40.101467, 'lon': -88.2385}",0 days 00:11:15,PLAZA:4
8,PLAZA:4,130N Silver,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@12.0.44184681@][1250945403296]/...,1354,{'stop_id': 'VETMED:1'},{'stop_id': 'ILBDWY:1'},True,True,True,2026-04-11 15:52:00-05:00,2026-04-11 15:54:40-05:00,24,"{'lat': 40.11286, 'lon': -88.217167}",0 days 00:02:40,PLAZA:4
9,PLAZA:4,100N Yellow,"{'route_color': 'fcee1f', 'route_id': 'YELLOW ...",{'trip_id': '[@15.0.63192124@][1][133841428066...,2421,{'stop_id': 'SWALMART:1'},{'stop_id': 'WALMART:2'},True,True,True,2026-04-11 15:58:00-05:00,2026-04-11 15:58:36-05:00,28,"{'lat': 40.0689, 'lon': -88.240883}",0 days 00:00:36,PLAZA:4
10,IU:1,130N Silver,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@12.0.44184681@][1250945403296]/...,2432,{'stop_id': 'PAR:2'},{'stop_id': 'ILBDWY:1'},True,True,True,2026-04-11 15:33:00-05:00,2026-04-11 15:35:13-05:00,4,"{'lat': 40.104033, 'lon': -88.221833}",0 days 00:02:13,IU:1
11,IU:1,220N Illini Limited,"{'route_color': '5a1d5a', 'route_id': 'ILLINI ...",{'trip_id': '[@6.0.14330204@][1][1622384291845...,2019,{'stop_id': 'ARC:2'},{'stop_id': 'LNCLNKLRNY:1'},True,True,True,2026-04-11 15:28:00-05:00,2026-04-11 15:39:00-05:00,8,"{'lat': 40.10145, 'lon': -88.238383}",0 days 00:11:00,IU:1
12,IU:1,20U Red,"{'route_color': 'ed1c24', 'route_id': 'RED SAT...",{'trip_id': '[@6.0.66478040@][42][174922413614...,2042,{'stop_id': 'WALMART:2'},{'stop_id': 'URBMEIJ:1'},True,True,False,2026-04-11 15:41:00-05:00,2026-04-11 15:42:28-05:00,11,"{'lat': 40.134117, 'lon': -88.2438}",0 days 00:01:28,IU:1
13,IU:1,120E Teal Orchard Downs,"{'route_color': '006991', 'route_id': 'TEAL SA...",{'trip_id': '[@12.0.44194660@][1250946648828]/...,1716,{'stop_id': 'IT:5'},{'stop_id': 'ODSS:1'},True,True,True,2026-04-11 15:42:00-05:00,2026-04-11 15:48:23-05:00,17,"{'lat': 40.103883, 'lon': -88.221867}",0 days 00:06:23,IU:1
14,IU:1,20U Red,"{'route_color': 'ed1c24', 'route_id': 'RED SAT...",{'trip_id': '[@6.0.66478040@][42][174922413614...,NaN,{'stop_id': 'WALMART:2'},{'stop_id': 'URBMEIJ:1'},False,True,False,2026-04-11 15:41:00-05:00,2026-04-11 15:48:34-05:00,18,"{'lat': 0, 'lon': 0}",0 days 00:07:34,IU:1
15,IU:1,50E Green,"{'route_color': '008063', 'route_id': 'GREEN S...","{'trip_id': 'GN5SAT014__GN4_SA', 'trip_headsig...",2044,{'stop_id': 'RNDBRNRD:2'},{'stop_id': 'ODSS:1'},True,True,False,2026-04-11 15:37:00-05:00,2026-04-11 15:51:19-05:00,20,"{'lat': 40.112783, 'lon': -88.279033}",0 days 00:14:19,IU:1
16,IU:1,130N Silver,"{'route_color': 'cccccc', 'route_id': 'SILVER ...",{'trip_id': '[@12.0.44184681@][1250945403296]/...,1354,{'stop_id': 'VETMED:1'},{'stop_id': 'ILBDWY:1'},True,True,True,2026-04-11 15:53:00-05:00,2026-04-11 15:55:40-05:00,25,"{'lat': 40.11286, 'lon': -88.217167}",0 days 00:02:40,IU:1

In [8]:
import io

resp = requests.get(
	"https://waf.cs.illinois.edu/discovery/course-catalog.csv",
	verify=False,  # disable SSL cert verification to avoid CERTIFICATE_VERIFY_FAILED
)
courses = pd.read_csv(io.StringIO(resp.text))

c:\Users\spkidz_su\sigaida_project\sigaida-guided-project\.venv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'waf.cs.illinois.edu'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [9]:
print(courses.columns)
print(courses["Credit Hours"].head(10))
print(courses["Credit Hours"].dtype)

Index(['Year', 'Term', 'YearTerm', 'Subject', 'Number', 'Name', 'Description',
       'Credit Hours', 'Section Info', 'Degree Attributes',
       'Schedule Information', 'CRN', 'Section', 'Status Code', 'Part of Term',
       'Section Title', 'Section Credit Hours', 'Section Status',
       'Enrollment Status', 'Type', 'Type Code', 'Start Time', 'End Time',
       'Days of Week', 'Room', 'Building', 'Instructors'],
      dtype='str')
0    3 hours.
1    3 hours.
2    3 hours.
3    3 hours.
4    3 hours.
5    3 hours.
6    3 hours.
7    3 hours.
8    3 hours.
9    3 hours.
Name: Credit Hours, dtype: str
str

In [10]:
courses.info()

<class 'pandas.DataFrame'>
RangeIndex: 12823 entries, 0 to 12822
Data columns (total 27 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Year                  12823 non-null  int64
 1   Term                  12823 non-null  str
 2   YearTerm              12823 non-null  str
 3   Subject               12823 non-null  str
 4   Number                12823 non-null  int64
 5   Name                  12823 non-null  str
 6   Description           12822 non-null  str
 7   Credit Hours          12823 non-null  str
 8   Section Info          11627 non-null  str
 9   Degree Attributes     2536 non-null   str
 10  Schedule Information  2725 non-null   str
 11  CRN                   12823 non-null  int64
 12  Section               12176 non-null  str
 13  Status Code           12823 non-null  str
 14  Part of Term          12595 non-null  str
 15  Section Title         1766 non-null   str
 16  Section Credit Hours  3257 non-null   str
 17  Section Status        12823 non-null  str
 18  Enrollment Status     12823 non-null  str
 19  Type                  12823 non-null  str
 20  Type Code             12823 non-null  str
 21  Start Time            12823 non-null  str
 22  End Time              9688 non-null   str
 23  Days of Week          9857 non-null   str
 24  Room                  8842 non-null   str
 25  Building              8884 non-null   str
 26  Instructors           11901 non-null  str
dtypes: int64(3), str(24)
memory usage: 2.6 MB

In [11]:
print(courses["Type"].unique())

<StringArray>
[    'Discussion/Recitation',                   'Lecture',
        'Lecture-Discussion',                    'Online',
         'Independent Study',                'Laboratory',
            'Online Lecture',     'Laboratory-Discussion',
         'Online Discussion',                'Conference',
                'Online Lab', 'Online Lecture Discussion',
                   'Seminar',              'Study Abroad',
                'Internship',                  'Research',
                    'Travel',                    'Studio',
                  'Practice',                      'Quiz',
          'Packaged Section']
Length: 21, dtype: str