In [ ]:
import pandas as pd
import requests
df = pd.read_csv("../data/trips.txt")

#Route: Silver
#Stops: PAR, Goodwin and Gregory, Gregory and Mumford, Illini Union
#trip_id: [@6.0.28932250@][1][1654525597845]/57__SV1_UIF
# scheduled vs expected = delay


#create a .py file 
#create a .csv file to write data
# run a while true function
# every time request, keep a timestamp of the request
# run as a background progress
#request and then sleep for a minute
df.head(10)

,route_id,service_id,trip_id,trip_headsign,trip_short_name,direction_id,block_id,shape_id,wheelchair_accessible,bikes_allowed
0,SILVER,SV1 UIF,[@6.0.28932250@][1][1654525597845]/57__SV1_UIF,North to PAR,NaN,0,SV1 UIF,[@6.0.28932250@]1,1,1
1,SILVER LATE NIGHT,SV1 UIMTH,[@12.0.42230752@][4][1246897581031]/20__SV1_UIMTH,South to PAR,NaN,1,SV1 UIMTH,SILVER LATE 30,1,1
2,PINK,P2 NOSCH MF,[@2.0.81838518@][12][1430161301181]/27__P2_NOS...,B to Round Barn Road,NaN,1,P2 NOSCH MF,[@2.0.81838518@]103,1,1
3,TEAL EVENING SATURDAY,T2 UI SA,[@124.0.92279199@][1484345597711]/38__T2_UI_SA,West to Illinois Terminal,NaN,1,T2 UI SA,[@124.0.92279199@]TEAL EVENING 12,1,1
4,GREEN,GN5 MF,5GN575__GN5_MF,West to Round Barn Road - Holiday Park,NaN,1,GN5 MF,5WPM->LSE,1,1
5,SILVER,SV4 SCH UIMTH,[@6.0.28932250@][1][1654213811517]/48__SV4_SCH...,North to Lincoln Square,NaN,0,SV4 SCH UIMTH,[@6.0.28932250@]1,1,1
6,ILLINI EVENING SATURDAY,I3 UISA,[@124.0.92260187@][1484328831455]/256__I3_UISA,North to Lincoln & Killarney,NaN,0,I3 UISA,[@124.0.92260187@]220N ILLINI 10,1,1
7,ILLINI,I1 UIMF,[@7.0.41200832@][1][1238430123625]/53__I1_UIMF,North to Lincoln & Anthony,NaN,0,I1 UIMF,[@15.0.63192528@]43,1,1
8,GREEN SATURDAY,GN3 UISA,[@7.0.41202550@][4][1248723584250]/1__GN3_UISA,West to Round Barn Road,NaN,1,GN3 UISA,[@15.0.68513015@]219,1,1
9,ILLINI LIMITED,I1 NONUI EVE,[@6.0.14327389@][1][1622146809102]/12__I1_NONU...,North to Lincoln & Killarney,NaN,0,I1 NONUI EVE,[@6.0.14327389@]10,1,1

In [ ]:
df_stoptimes = pd.read_csv("../data/stop_times.txt")
df_stoptimes[df_stoptimes["trip_id"] == "[@6.0.28932250@][1][1654213811517]/48__SV4_SCH_UIMTH"]
df_stoptimes["route_name"] = "Silver"
df_stoptimes.head(20)

,trip_id,arrival_time,departure_time,stop_id,stop_sequence,stop_headsign,pickup_type,drop_off_type,timepoint,route_name
0,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:26:00,19:26:00,PAR:2,1,NaN,0,0,0,Silver
1,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:00,19:27:00,PAMD:2,2,NaN,0,0,0,Silver
2,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:45,19:27:45,PSL:2,3,NaN,0,0,0,Silver
3,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:28:20,19:28:20,GRGDNR:2,4,NaN,0,0,0,Silver
4,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:28:55,19:28:55,GWNGRG:1,5,NaN,0,0,0,Silver
5,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:29:30,19:29:30,GRGMUM:2,6,NaN,0,0,0,Silver
6,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:30:05,19:30:05,GRGLIB:2,7,NaN,0,0,0,Silver
7,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:31:15,19:31:15,ARYWRT:5,8,NaN,0,0,0,Silver
8,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:31:50,19:31:50,PLAZA:4,9,NaN,0,0,0,Silver
9,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:33:00,19:33:00,IU:1,10,NaN,0,0,0,Silver
10,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:34:30,19:34:30,GDWNMRL:2,11,NaN,0,0,0,Silver
11,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:35:00,19:35:00,SPFLDHVY:3,12,NaN,0,0,0,Silver
12,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:35:30,19:35:30,SPFLDGRGST:3,13,NaN,0,0,0,Silver
13,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:36:30,19:36:30,SPFLDBSY:3,14,NaN,0,0,0,Silver
14,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:37:30,19:37:30,SPFLDPRC:1,15,NaN,0,0,0,Silver
15,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:38:00,19:38:00,SPFLDBRCH:3,16,NaN,0,0,0,Silver
16,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:40:00,19:40:00,LSE:8,17,NaN,0,0,0,Silver
17,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:26:00,19:26:00,PAR:2,1,NaN,0,0,0,Silver
18,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:00,19:27:00,PAMD:2,2,NaN,0,0,0,Silver
19,[@12.0.42224456@][3][1246897112109]/0__SV4_NOS...,19:27:45,19:27:45,PSL:2,3,NaN,0,0,0,Silver

In [ ]:
url = "https://developer.mtd.org/api/v2.2/json/getdeparturesbystop?key=c097f4c423e7471eb40a606d859ce9e0&stop_id=GRGMUM:2"

In [ ]:
response = requests.get(url)
data = response.json()
departures = data["departures"]
df_departures = pd.DataFrame(departures)

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   stop_id        5 non-null      str
 1   headsign       5 non-null      str
 2   route          5 non-null      object
 3   trip           5 non-null      object
 4   vehicle_id     5 non-null      str
 5   origin         5 non-null      object
 6   destination    5 non-null      object
 7   is_monitored   5 non-null      bool
 8   is_scheduled   5 non-null      bool
 9   is_istop       5 non-null      bool
 10  scheduled      5 non-null      str
 11  expected       5 non-null      str
 12  expected_mins  5 non-null      int64
 13  location       5 non-null      object
dtypes: bool(3), int64(1), object(5), str(5)
memory usage: 587.0+ bytes
None

In [ ]:
df_departures

Empty DataFrame
Columns: []
Index: []

In [ ]:
stops = ["PAR:2", "ARYWRT:5", "PLAZA:4", "IU:1", "LSE:8"]
all_departures = []

for stop in stops: 
    url = f"https://developer.mtd.org/api/v2.2/json/getdeparturesbystop?key=c097f4c423e7471eb40a606d859ce9e0&stop_id={stop}"
    response = requests.get(url)
    data = response.json()
    departures = data.get("departures", [])
    print (departures)
    df_res = pd.DataFrame(departures)
    print(df_res.info()) #check for the correct headsign
    df_res["delay"] = df_res.expected - df_res.scheduled #finds the delay
    df_res["queried_stop"] = stop
    all_departures.append(df_res)
    

df_all = pd.concat(all_departures, ignore_index = True)

[]
[]
[]
[]
[]
<class 'pandas.DataFrame'>
RangeIndex: 0 entries
Data columns (total 1 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   queried_stop  0 non-null      str
dtypes: str(1)
memory usage: 132.0 bytes

In [15]:
df_all

Empty DataFrame
Columns: [queried_stop]
Index: []